FIX: vcpkg build
For some reason the working directory is not working.

error: invalid character in port name (must be lowercase, digits, '-')
  on expression: working_directory

There were no changes, so maybe something has changed in the vcpkg-tool.