FIX: CMake issue
Missing current source directory inclusion.

/Users/runner/work/vanillapdf/vanillapdf/src/vanillapdf/implementation/c_values.cpp:1:10: fatal error: 'precompiled.h' file not found
#include "precompiled.h"