Small fixes (#15)
* FIX: Comment typo

* TWEAK: Update year

* TWEAK: License change

* NEW: Include NOTICE

* NEW: Enable osx-arm64

* TWEAK: Update readme

* FIX: Linux warning

On latest ubuntu there were conversion warnings.

* TWEAK: CMake source dir

Switch to CMAKE_CURRENT_SOURCE_DIR from CMAKE_SOURCE_DIR.
When including this in the python wrapper,
the CMAKE_SOURCE_DIR is pointing to the root project.
We need to reference the subproject inside,
so that vcpkg can be properly bootstrapped.

* TWEAK: CMake source dir

More occurences of current source dir issues

* TWEAK: More source dir changes

Neither of the subprojects anticipated to be included by another repository.
Let's see if we got it right now, as locally this works.

* TWEAK: cmake source dir

vcpkg triplet issues resolution

* FIX: Source dir

Move definition of value so it is available also for bootstrap

* FIX: CMake issue

Missing current source directory inclusion.

/Users/runner/work/vanillapdf/vanillapdf/src/vanillapdf/implementation/c_values.cpp:1:10: fatal error: 'precompiled.h' file not found
#include "precompiled.h"

* TWEAK: vcpkg triplet

Automatic detection of vcpkg triplet, so when it is invoked from python

* FIX: Add missing includes

* FIX: vcpkg build

For some reason the working directory is not working.

error: invalid character in port name (must be lowercase, digits, '-')
  on expression: working_directory

There were no changes, so maybe something has changed in the vcpkg-tool.

* FIX: vcpkg dependencies

One more try to fix installation of dependencies within python build env

* TWEAK: vcpkg directory

With pipenv shell we got a bit futher, that the dependencies were actually built.
The issue is still with searching for them.

      CMake Error at C:/Program Files/CMake/share/cmake-4.0/Modules/FindPackageHandleStandardArgs.cmake:227 (message):
        Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
        system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
        OPENSSL_INCLUDE_DIR)

* FIX: cmake include path

Header include files do not work in remote repos - python

* FIX: vcpkg toolchain

Toolchain file needs to be included to work - not only defined

* FIX: Private linking

Python wrapper refused to find CXX compiler,
unless this was marked as private.
Private means that the dependencies should not be propagated further,
which is correct in this case.

* FIX: vcpkg bootstrap

On macOS the runner cannot find OpenJPEG and the OpenSSL is
pointing to incorrect location.

Let's try to improve the vcpkg bootstrap process and also include
toolchain file explicitly in the cmd parameters.

* FIX: vcpkg bootstrap

The workflow is not valid. .github/workflows/sanity-check.yml
(Line: 40, Col: 28): Unrecognized named-value: 'env'.
Located at position 1 within expression: env.VCPKG_ROOT

* FIX: vcpkg bootstrap

Matrix values like bootstrap_cmd are evaluated before the job starts,
so they can’t reference runtime environment variables like ${{ env.FOO }}

* FIX: vcpkg bootstrap

The workflow is not valid. .github/workflows/sanity-check.yml
(Line: 65, Col: 16): Unrecognized named-value: 'matrix'.
Located at position 1 within expression: matrix.shell

* FIX: vcpkg bootstrap

The workflow is not valid. .github/workflows/sanity-check.yml
(Line: 67, Col: 16): Unrecognized named-value: 'matrix'.
Located at position 1 within expression: matrix.shell

* FIX: vcpkg bootstrap

Indentation error

* FIX: vcpkg bootstrap

workspace, out-of-source build, triplets

* FIX: vcpkg bootstrap

CMakePresets and toolchain

* FIX: vcpkg bootstrap

CMakePresets

* FIX: vcpkg bootstrap

Switch to manifest mode, add build/test presets, linking error fix

* FIX: vcpkg bootstrap

Remove skia by default, install mising build tools

* FIX: Compilation error

macOS cannot build benchmark due to c++17 features.
Windows is failing due to linking hacks /MT.

* FIX: Warnings

GCC with pedantic is triggerring a lot of errors, so let's address them.
Disable unused parameter warning as it is not a bug.

* FIX: unittest build

Let's unify the private dependencies also here.

* TWEAK: sanity check

Added nighly check, that does release build and test on all platforms.
Added vcpkg caching experimental.

* TWEAK: Disable pedantic

This triggers really obscure warnings and some of them cannot be disabled

* FIX: CMakePresets

Caching, msvc x64 was missing and switch sanity check to release

* FIX: Syntax .yml

* FIX: CMakePresets

Missing x64 for windows clang

* FIX: GCC warnings

Unused parameters should not be reported as warnings

* TWEAK: vcpkg manifest

Cleanup the old dependency management file
once we have switched to manifest mode.

* FIX: Windows cache

Rebuilding project on windows is having issues with the cache.
Let's try to use triplet instead of preset for caching.

* FIX: vcpkg bootstrap

Windows is having issues with legacy.dll, which was not cached.
The bootstrap functionality was extracted into separate action.

* FIX: github action typo