Tests and optimizations (#42)
* TWEAK: Disable Logging

Logging is unfortunately enabled by default,
let's disable it for benchmarking.

* NEW: Test cases CheckPrintableError

Based on code coverage let's start adding easy-win test cases.

* NEW: Benchmark scenarios

Prepare for string_view optimizations to measure CreateFromEncodedString.

* TWEAK: Use FromChars where possible

Use FromChars instead of stoi/stod/stoull to reduce number of allocations.
Slight performance upgrades here and there up to 10% - done the benchmarking.
Since this change is cross many files I don't know where to store the bencharking results.
I don't see any downsides to this, so let's change it in all places.

* TWEAK: Benchmark cleanup

Use const char * instread of std::string to reduce allocations.
Move it out of the work cycle, since it might affect the benchmark itself.

* NEW: EncodedString NameObject

Add new benchmark to test NameObject creation and decoding speed.

* TWEAK: Unit test namespaces

All objects were added into objects namespace.
New NameObject tests, including hexadecimal notation.

* TWEAK: NameObject performance

CreateFromEncoded significant improvements.

* TWEAK: StringObject cleanup

Deduplicate SetValue and SetRawValue.

* NEW: MemoryBufferOutputStream

New implementation of IOutputStream using fmt::memory_buffer.
Performance improvements for Object ToStream and ToPdf,
from 10%-50% depdending on the type and complexity.
Overall test cases runtime down by ~10%.

* TWEAK: Update formatting

Namespaces should not be indented.

* TWEAK: Formatting

Namespace indentation.

* FIX: Compilation error

We have removed the need for template specialization using constexpr if.
error: explicit specialization in non-namespace scope 'class vanillapdf::MiscUtils'

* FIX: FromChars on mac

MAC does not support std::from_chars for double.
We add compile time check if the compiler supports it.
If not, we fallback to template specialization, that uses strtod.

* FIX: License check warning

* TWEAK: Cleanup buffer constructors

On Linux a different Buffer constructor was used and it created empty data.
This triggered an assertion which was not correct.

We have removed some conflicting constructors,
moved the implementation to header so it can be inlined if needed.

Simplify NameObject constants creation using stringview directly.

* FIX: Mac compilation

Mac is having linking issues, when the specialization is not marked as inline.

* NEW: More test cases

CreateFromData multiple scenarios.

* FIX: Log missing value

* TWEAK: Unit test refactoring

Split into more files - utils and objects.
Extend NameObject tests with multiple scenarios.

* TWEAK: Remove unit test

The test of 1024 characters extend the test output in terms of width.
It does not add any extra value, so we can safely remove it.

* NEW: MemoryBufferOutputStream API

Expose MemoryBufferOutputStream object on the library interface.
Added unit tests to keep up the code coverage.