FIX: GCC 8.5 linker error
undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'

Using this library may require additional compiler/linker options.
GNU implementation prior to 9.1 requires linking with -lstdc++fs and
LLVM implementation prior to LLVM 9.0 requires linking with -lc++fs.